### ISSUE TITLE
Where can we find the RemoteControl plugin apis syntax details?

### ISSUE THREAD

**Issue by nandishyb** [McKael/samtv#10]
I see that to send the remote key below is used:
`{"method":"POST","body":{"plugin":"RemoteControl","param1":"uuid:` +
		s.uuid + `","param2":"Click","param3":"` + keyPressed +
		`","param4":false,"api":"SendRemoteKey","version":"1.000"}}`

Similarly, I want to know how to how send mouse movement update 
Below is example for latest TVs by I needed similar api for 2014 and 2015 tvs `{"method":"ms.remote.control","params":{"Cmd":"Move","Position":{"x":0,"y":0,"Time":"` + ts() + `"},"TypeOfRemote":"ProcessMouseDevice"}}

Where can we find the RemoteControl plugin apis syntax details?

**Comment by McKael** [comment]
I have no idea (and I doubt this is even possible with those models).
