### ISSUE TITLE
no httptrace package 

### ISSUE THREAD

**Issue by freezah** [McKael/samtv#2]
Hi there,

When trying to download samtvcli via go I get following errors, which prevents me from building samtvcli:

go get -u github.com/McKael/samtv/samtvcli
package github.com/McKael/samtv/samtvcli
	imports github.com/McKael/samtv
	imports github.com/McKael/smartcrypto
	imports github.com/pkg/errors
	imports github.com/gorilla/websocket
	imports context: unrecognized import path "context"
package github.com/McKael/samtv/samtvcli
	imports github.com/McKael/samtv
	imports github.com/McKael/smartcrypto
	imports github.com/pkg/errors
	imports github.com/gorilla/websocket
	imports net/http/httptrace: unrecognized import path "net/http/httptrace"

 uname -a
Linux rasp_zerow 4.4.50+ #970 Mon Feb 20 19:12:50 GMT 2017 armv6l GNU/Linux

go version
go version go1.3.3 linux/arm

**Comment by McKael** [comment]
Hi,

Your Golang version is way too old.  Please check https://github.com/McKael/samtv/issues/1#issuecomment-436690680 or try to use the prebuilt release binaries.
