### ISSUE TITLE
Thank you for creating samtv!

### ISSUE THREAD

**Issue by jorisroovers** [McKael/samtv#4]
Hi!

I just wanted to leave a short thank you note for creating and open-sourcing samtvcli. I've spend the last year or so sporadically looking for a way to **easily** automate some basic actions on my UE48H6200AW Samsung TV. This is the first tool I've encountered that doesn't require me to write code myself to get the job done (which wasn't something I wanted to spend time on).

Having done some open-source work myself in the past, I know how much time and effort it costs to create and maintain small projects like these. Please know that you've made a random internet stranger's day!

Thank you!!

**Comment by McKael** [comment]
Thanks @jorisroovers !

You're welcome,
I'm glad I could help :)

It's good to see some other people like it and find it useful... thanks for letting me know!

Nice to see such a bug report ;-)  :+1:

**Comment by mStirner** [comment]
@McKael  Thank you very much! 

I searched for so long why my UE60J6240 did not work, but my newer UE43KU6079 over a simple WebSocket connection.
Then i sniffed the traffic from the SmartView app, analyzed it and wonderd about the handshake and paring messages. 

Searched then for "auth type SPC, GeneratorServerHello" and found your pair.go file! 

**Thank you very much for this tool!**

I hope its ok if i port the pairing part to node.js?

**Comment by McKael** [comment]
> I hope its ok if i port the pairing part to node.js?

Sure! :+1:
