### ISSUE TITLE
Option to set volume level needed

### ISSUE THREAD

**Issue by rodajc** [McKael/samtv#6]
This tool, samtvcli, is the only tool communicating with my TV, so I'm grateful already. But, it would be even better is it was possible to set a volume level. Of course KEY_VOLDOWN and KEY_VOLUP are there, but you need feedback to be able to adjust the volume to a certain level. The samsungctl tool has an command line option --volume for this. Unfortunately samsungctl doesn't work for me at all.
Would it be possible to add this option to samtvcli?

**Comment by McKael** [comment]
Sorry for the huge delay...

I don't think this is possible at all with those models.  As far as I know, we can only imitate a remote, and it isn't possible to specify a volume level.
