### ISSUE TITLE
Support for UE32J5200AWXXN

### ISSUE THREAD

**Issue by metbril** [McKael/samtv#9]
I've tried the tool with the **UE32J5200AWXXN** model, but am unable to pair:

```
 $ ./samtvcli --config .samtvcli.yaml --debug pair
INFO[0000] Using config file: .samtvcli.yaml
DEBU[0000] Initiating step #0
DEBU[0000] PIN page is stopped
INFO[0000] Requesting PIN page popup...
DEBU[0000] PIN page response: `http://192.168.1.122:8080/ws/apps/CloudPINPage/run`
DEBU[0000] Fetch URL: http://192.168.1.122:8080/ws/pairing?step=0&app_id=samtvcli&device_id=samtv&type=1
DEBU[0000] Pairing request response: `{"auth_data":""}

`
```

Would you be able to help me with this?

**Comment by metbril** [comment]
Hmmmm. The MiTifi app also doesn't work:

https://imkapps.com/mytifi/manual/#TOC-No-PIN-Code-shown

> If your TV doesn’t show a PIN code, your TV is probably not compatible. These are TVs like J5200, J5300, J5205, J6203, J620D, etc. See the list of compatible models.

It looks like I'm out of luck...

**Comment by McKael** [comment]
@metbril I'm afraid I won't be of much help.  The only TV I can use for tests is my own, and it doesn't look like yours is compatible.

Sorry!

**Comment by metbril** [comment]
Thanks for the reply. You might want to add some information about supported models to your documentation / the README. You could learn from the MyTifi page I referred to.
